{{- if .Values.security.enabled -}}
# This is a simple example of using a config map to create a single page static site.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-usersd 
  labels:
    app: {{ .Release.Name }}-usersd
    chart: {{ template "clickhouse-on-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  users.xml: |-
    <yandex>
        <!-- Profiles-->
        <profiles>
            {{- range .Values.security.profiles }}
            <{{ .name }}>
                <!-- Maximum memory usage for processing single query, in bytes. -->
                <max_memory_usage>{{ int64 .max_memory_usage | default 10000000000 }}</max_memory_usage>

                <!-- Use cache of uncompressed blocks of data. Meaningful only for processing many of very short queries. -->
                <use_uncompressed_cache>{{ int64 .use_uncompressed_cache | default 0 }}</use_uncompressed_cache>

                <load_balancing>{{ .load_balancing | default "random" }}</load_balancing>
            </{{ .name }}>
            {{- end }}

            <!-- readonly profile -->
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>

        <!-- Quotas -->
        <quotas>
            {{- range .Values.security.quotas }}
            <{{ .name }}>
                <!-- Limits for time interval. You could specify many intervals with different limits. -->
                <interval>
                    <!-- Length of interval. -->
                    <duration>{{ int64 .duration | default 3600 }}</duration>

                    <!-- No limits. Just calculate resource usage for time interval. -->
                    <queries>{{ int64 .queries | default 0 }}</queries>
                    <errors>{{ int64 .errors | default 0 }}</errors>
                    <result_rows>{{ int64 .result_rows | default 0 }}</result_rows>
                    <read_rows>{{ int64 .read_rows | default 0 }}</read_rows>
                    <execution_time>{{ int64 .execution_time | default 0 }}</execution_time>
                </interval>
            </{{ .name }}>
            {{- end }}
        </quotas>

        <!-- Users --> 
        <users>
            {{- range .Values.security.users }}
            <{{ .name }}>
                <password>{{ .password }}</password>
            
                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>

                <!-- Settings profile for user. -->
                <profile>{{ .profile | default "default" }}</profile>

                <!-- Quota for user. -->
                <quota>{{ .quota | default "default" }}</quota>
            </{{ .name }}>
            {{- end }}
            
            <!-- User for distributed queries -->
            <{{ .Values.security.distributed.user }}>
                <password>{{ .Values.security.distributed.password }}</password>

                <networks incl="networks" replace="replace">
                    <ip>::/0</ip>
                </networks>

                <!-- Settings profile for user. -->
                <profile>{{ .Values.security.distributed.profile | default "default" }}</profile>

                <!-- Quota for user. -->
                <quota>{{ .Values.security.distributed.quota | default "default" }}</quota>
            </{{ .Values.security.distributed.user }}>

            <readonly>
                <password></password>
                <networks incl="networks" replace="replace">
                    <ip>::1</ip>
                    <ip>127.0.0.1</ip>
                </networks>
                <profile>readonly</profile>
                <quota>default</quota>
            </readonly>
        </users>
    </yandex>
{{- end }}
