{{- if .Values.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:  
  name: patch-pod
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:  
  name: default:patch-pod
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-pod
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{- end }}